### ISSUE TITLE
Incorrect step order for ECS module instructions

### ISSUE THREAD

**Issue by igorroyzis** [mandusm/aws-modernization-workshop#142]
Steps 14 and 15 need to be swapped.

14. Set the Health check grace period to 300. Note: This is the period of time, in seconds, that the Amazon ECS service scheduler should ignore unhealthy Elastic Load Balancing target health checks after a task has first started. This is only valid if your service is configured to use a load balancer. If your service’s tasks take a while to start and respond to health checks, you can specify a health check grace period of up to 7,200 seconds during which the ECS service scheduler ignores the health check status. This grace period can prevent the ECS service scheduler from marking tasks as unhealthy and stopping them before they have time to come up.

15. Under Load Balancing, select the Application Load Balancer and make sure petstore-lb is selected.

**Comment by mandusm** [comment]
This has been addressed.
