### ISSUE TITLE
Deploy the Workshopper Environments

### ISSUE THREAD

**Issue by mandusm** [mandusm/aws-modernization-workshop#19]
Deploy the ECS Fargate hsoted workshopper tasks to deliver
dev.modernize.awsworkshop.io
modernize.awsworkshop.io

**Comment by mandusm** [comment]
See no reason why this repo needs to be private. Making it public.

**Comment by mandusm** [comment]
Deployed master branch to https://modernize.awsworkshop.io

**Comment by christopherhein** [comment]
can we remove `blocked` label from this?

**Comment by mandusm** [comment]
Removed.

**Comment by christopherhein** [comment]
Did you finish this? @mandusm

**Comment by rniksch** [comment]
this is complete to my understanding
