### ISSUE TITLE
Integrate jPetstore Maven Build with Artifactory 

### ISSUE THREAD

**Issue by mandusm** [mandusm/aws-modernization-workshop#36]
Showcase the configuration of your Artifacts to import maven dependencies into artifactory and build against artifactory storage.

**Comment by jayyeras** [comment]
@mandusm what do you think about adding another CFT for Jenkins, setup the [AWS CodeCommit Trigger Plug-in](https://wiki.jenkins.io/display/JENKINS/AWS+CodeCommit+Trigger+Plugin) and then the [Artifactory Jenkins Plug-in](https://www.jfrog.com/confluence/display/RTF/Jenkins+Artifactory+Plug-in) for this section?

**Comment by jayyeras** [comment]
@mandusm we won't have time to do as I proposed last week for this version. instead let's model the workflow off erin's [post](https://aws.amazon.com/blogs/devops/integrating-jfrog-artifactory-with-aws-codepipeline/)

**Comment by mandusm** [comment]
This issue was addressed in PR #57
