### ISSUE TITLE
Missing kubectl binaries in Cloud9

### ISSUE THREAD

**Issue by jayyeras** [mandusm/aws-modernization-workshop#55]
container-orchestration module step 7 assumes kubectl is installed in environment, but does not contain instructions on doing so.

**Comment by mandusm** [comment]
We can use the content from https://github.com/mandusm/howto-launch-eks-workshop/tree/master/modules/eks-tools to install the EKS tools. 

The update step for Cloud9 and AWS CLI is just running
```
pip install --upgrade --user awscli pip
```

We will add this to the `Getting Started Guide`

**Comment by jayyeras** [comment]
I didn't see this in Getting Started module.

**Comment by christopherhein** [comment]
@jayyaras this is in **Step 2:** second line in the Getting Started Guide

**Comment by christopherhein** [comment]
closed in #87
