### ISSUE TITLE
No instructions for creating ECR Repository

### ISSUE THREAD

**Issue by mandusm** [mandusm/aws-modernization-workshop#58]
We are not providing the attendees with instructions on how to create the ECR repository.
We jump directly into "push docker image to ECR" 

We need to create the ECR repositories. 
https://docs.aws.amazon.com/cli/latest/reference/ecr/create-repository.html

```
aws ecr create-repository --repository-name
```

**Comment by christopherhein** [comment]
it's in the cloudformation templates for fargate.

**Comment by mandusm** [comment]
Oh man. I missed it. I see it now. 
Cool.
