### ISSUE TITLE
CI Workshop

### ISSUE THREAD

**Issue by mandusm** [mandusm/aws-modernization-workshop#6]
Continious Integration. Let's walk through a simple CI integration

**Comment by jayyeras** [comment]
@mandusm I think it would make sense to begin this module with talking points on best practices. I can reuse talking points from SRV320 and we can then move to the hands on portion of the lab where we launch the templates and work through some examples. i.e. Why does CI/CD matter? Automated testing, Continuous production testing, Managing deployment health, Segment production, halting promotions. Thoughts?

**Comment by mandusm** [comment]
We will be talking about why CI/CD in the opening presentation. Is there anything specific you would want to add before the Lab?

**Comment by jayyeras** [comment]
Mainly, the techniques listed in my last sentence.
