### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by jayyeras** [mandusm/aws-modernization-workshop#76]
player-role:~/bin $ eksctl create cluster --full-ecr-access --name=petstore\
2018-08-28T16:01:35Z [✖]  heptio-authenticator-aws not installed

Is that expected result?

**Comment by jayyeras** [comment]
`aws configure` should be added to this section

**Comment by jayyeras** [comment]
`AWS_DEFAULT_REGION=us-west-2` needs to be added to Getting Started. Disregard previous comment.

**Comment by christopherhein** [comment]
Looks like the script downloads to the home directory instead of the `~/bin` for the `heptio-authenticator-aws` binary
