### ISSUE TITLE
Artifactory

### ISSUE THREAD

**Issue by jayyeras** [mandusm/aws-modernization-workshop#78]
`aws cloudformation create-stack --stack-name "artifactory-oss" --template-body=file://modules/artifactory/artifactory-oss.yml --parameters ParameterKey=ClusterName,ParameterValue="artifactory-oss" --capabilities CAPABILITY_IAM` needs to have `cd` to `~/environment/aws-modernization-workshop` before execution.

**Comment by christopherhein** [comment]
I think we should make this `cd ~/environment/aws-modernization-workshop/modules/artifactory/` like then shorten the cft create stack commands
