### ISSUE TITLE
Container Orchestration - Deploy our VPC and ECR Repositories

### ISSUE THREAD

**Issue by jayyeras** [mandusm/aws-modernization-workshop#82]
`aws cloudformation create-stack --stack-name "petstore" --template-body file://petstore-fargate-cf-resources.yaml --capabilities CAPABILITY_NAMED_IAM` copy+paste not working.

`ACCOUNT_ID=$(aws ecr describe-repositories --repository-name petstore_frontend --query=repositories[0].repositoryUri --output=text | cut -d"." -f1)
echo ${ACCOUNT_ID}
sed -i "s/<YourAccountID>/${ACCOUNT_ID}/" petstore-fargate-task-definition.json` copy+paste not working.

**Comment by rniksch** [comment]
again I am not seeing any issues with copy and paste control.
