### ISSUE TITLE
Container Orchestration - Amazon EKS and Kubernetes Manifests

### ISSUE THREAD

**Issue by jayyeras** [mandusm/aws-modernization-workshop#83]
`kubectl apply -f petstore-eks-manifest.yaml` returns `Unable to connect to the server: getting token: exec: exec: "heptio-authenticator-aws": executable file not found in $PATH`

**Comment by christopherhein** [comment]
We need to backtrack cause the issues you are filing are due to getting started not being correct. should be closed via #76
