### ISSUE TITLE
Automation 

### ISSUE THREAD

**Issue by jayyeras** [mandusm/aws-modernization-workshop#85]
**Getting Started:**
Need to include instructions to navigate to `~/environment/aws-modernization-workshop`

**Cloning your CodeCommit Repo - Step 5:**
`git push -f codecommit master` returns `fatal: I don't handle protocol '"https'` 
This is caused by CloneURL being passed with quotes.

**Comment by jayyeras** [comment]
CodeBuild fails: `[Container] 2018/08/28 17:50:38 Phase complete: DOWNLOAD_SOURCE Success: false`

**Comment by mandusm** [comment]
The `buildspec.yml` is not in the root of this repo.
Either move it to root from the cicd module, or change the path in the `CodeBuild` project defintion. 

https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-name-storage

**Comment by jayyeras** [comment]
Resolved in [pull request 103](https://github.com/mandusm/aws-modernization-workshop/pull/103)
