### ISSUE TITLE
Managing Artifacts

### ISSUE THREAD

**Issue by mandusm** [mandusm/aws-modernization-workshop#9]
Where should I be storing and building Artifacts from?

**Comment by jayyeras** [comment]
**Note:** We will be supporting OSS in the lab. This means that we will not have high-availability or S3 support for storage of artifacts. Also, OSS only [supports: Maven, Gradle and Ivy](https://jfrog.com/open-source/) which should suffice for our purposes. I will provide a sample reference architecture supporting HA and S3 based as well as a CloudFormation template that can be "taken home" for later deployment. This will support Pro and Enterprise versions which support HA/S3.
