### ISSUE TITLE
Unable to locate credentials

### ISSUE THREAD

**Issue by CarmenAPuccio** [mandusm/aws-modernization-workshop#97]
The Getting Started Guide has the user turning off the temporary credentials and then running the below command which results in an error stating unable to locate credentials. If you reverse the steps it works fine. 

aws ec2 associate-iam-instance-profile \
  --instance-id $(aws ec2 describe-instances \
    --filters Name=tag:Name,Values="*cloud9*" \
    --query Reservations[0].Instances[0].InstanceId \
    --output text) --iam-instance-profile Name="cl9-workshop-role"

**Comment by christopherhein** [comment]
Will update thanks!
